---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-noop-cni-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: noop-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: noop-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kube-noop-cni
          image: centos:latest
          command: ["/bin/sh"]
          args: ["-c", "echo '#!/bin/sh\necho \"{\\\"result\\\": []}\"' > /host/opt/cni/bin/noop; chmod +x /host/opt/cni/bin/noop; sleep infinity"]
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
