apiVersion: batch/v1
kind: Job
metadata:
  name: sriov-config-job
  namespace: kube-system
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 100
  template:
    spec:
      hostNetwork: true
      containers:
      - name: sriov-config
        image: booxter/sriov-config
        securityContext:
          privileged: true
        volumeMounts:
          - name: pcidp
            mountPath: /host/etc/pcidp/
            readOnly: false
      restartPolicy: Never
      volumes:
        - name: pcidp
          hostPath:
            path: /etc/pcidp/
